# Generated by Django 3.0.5 on 2020-07-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='contact',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
    ]
