# Generated by Django 3.0.5 on 2020-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20200722_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='post_as',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumedata',
            name='post_qs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='key_skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='work_experience',
            field=models.TextField(null=True),
        ),
    ]
