# Generated by Django 3.0.5 on 2020-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_auto_20200731_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedata',
            name='post_qs',
            field=models.TextField(default='["My journey at job", "My expectations from final year", "How my site is structured and django", "How I used TDD to develop my app"]'),
        ),
    ]
